/**
 * T018 (US1): 跨 family 越权访问日志集成测试。
 *
 * FR-008 / SC-005:当用户 A 试图访问 family B 的 transaction 时,
 * procedure 抛 NOT_FOUND(不暴露资源存在性),日志应记 warn 级
 * `event:"authz.cross_family_attempt"`(含访问者 userId + 被访问资源 id)。
 *
 * 跨 family 检测在 procedure 层:get 路径在加载 transaction 后比对
 * transaction.familyId 与 ctx.session 的 familyId,不匹配则抛 NOT_FOUND。
 * 本测试在真实 PG 环境验证该路径 + 日志事件触发。
 *
 * 注:cross_family_attempt 的 warn 触发逻辑在 transaction.get 的
 * familyId 比对失败分支。若该分支尚未接入 event 日志,本测试会 RED ——
 * 届时需在 transaction.ts 的 get procedure 加上显式 logger.warn 调用。
 */
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { startTestDb, stopTestDb, type TestDb } from "@/tests/helpers/db";
import { db } from "@/server/db/client";
import {
  transaction,
  account as accountTable,
  family,
  member,
  user,
  category,
} from "@/server/db/schema";
import { createCaller } from "@/lib/trpc/server";
import { newId } from "@/lib/uuid";

const { loggerCalls, captureCall } = vi.hoisted(() => {
  const calls: Array<{ level: string; payload: any; msg: any }> = [];
  const capture = (level: string) =>
    function (this: unknown, payload: any, ...rest: any[]) {
      calls.push({ level, payload, msg: rest[0] });
      return this;
    };
  return { loggerCalls: calls, captureCall: capture };
});

vi.mock("@/lib/logger", () => {
  const stub = {
    info: captureCall("info"),
    warn: captureCall("warn"),
    error: captureCall("error"),
    debug: captureCall("debug"),
    child: () => stub,
    level: "info",
  };
  return { logger: stub, isSlow: () => false, SLOW_THRESHOLDS_MS: {} };
});

let testDb: TestDb | undefined;

beforeAll(async () => {
  process.env.DATABASE_URL = "placeholder-overridden-below";
  testDb = await startTestDb();
});

afterAll(async () => {
  if (testDb) await stopTestDb(testDb);
});

async function seedFamilyWithTransaction(emailSuffix: string) {
  const userId = `u-${newId().slice(0, 12)}`;
  const famId = newId();
  const memId = newId();
  const accId = newId();

  await db.insert(user).values({
    id: userId, email: `t018-${emailSuffix}-${Date.now()}@example.com`,
    emailVerified: false, name: "test", image: null,
  });
  await db.insert(family).values({ id: famId, ownerUserId: userId, name: `家庭${emailSuffix}` });
  await db.insert(member).values({
    id: memId, familyId: famId, userId, displayName: `member-${emailSuffix}`,
  });
  await db.insert(accountTable).values({
    id: accId, familyId: famId, name: `账户${emailSuffix}`, currency: "CNY", initialBalance: 0,
  });

  const cats = await db.select().from(category);
  const expenseCat = cats.find((c) => c.type === "expense")!;

  // Seed one transaction in this family (id auto-generated by $defaultFn uuidv7).
  // transaction schema has no memberId column — member is implicit via family.ownerUserId.
  const inserted = await db.insert(transaction).values({
    familyId: famId, accountId: accId,
    categoryId: expenseCat.id, type: "expense", amount: -500,
    remark: "", occurredAt: new Date("2026-07-19"),
  }).returning({ id: transaction.id });
  const txId = inserted[0]!.id;

  return { userId, famId, memId, accId, txId };
}

function caller(userId: string) {
  return createCaller({
    session: {
      user: {
        id: userId, email: "test@example.com", emailVerified: false,
        name: "test", image: null, createdAt: new Date(), updatedAt: new Date(),
      },
      session: {
        id: "s_test", userId, token: `tok-${newId()}`,
        expiresAt: new Date(Date.now() + 86_400_000), ipAddress: null,
        userAgent: null, createdAt: new Date(), updatedAt: new Date(),
      },
    },
  });
}

describe("[T018 / US1] 跨 family 越权 → NOT_FOUND + warn event (FR-008, SC-005)", () => {
  it("user A accessing family B's transaction → NOT_FOUND + cross_family_attempt warn", async () => {
    const familyA = await seedFamilyWithTransaction("a");
    const familyB = await seedFamilyWithTransaction("b");

    const cA = caller(familyA.userId);

    loggerCalls.length = 0;

    // User A tries to GET family B's transaction
    await expect(
      cA.transaction.get({ id: familyB.txId }),
    ).rejects.toMatchObject({ code: "NOT_FOUND" });

    // timingMiddleware logs an error (NOT_FOUND is a failed result.ok).
    const errorCalls = loggerCalls.filter((c) => c.level === "error");
    expect(errorCalls.length).toBeGreaterThanOrEqual(1);
    const rec = errorCalls[0]!;
    expect(rec.payload.code).toBe("NOT_FOUND");
    expect(rec.payload.path).toBe("transaction.get");

    // FR-008: the cross-family warn event is emitted by transaction.get's
    // family-mismatch branch (wired as of US1).
    const warnEvents = loggerCalls.filter(
      (c) => c.level === "warn" && c.payload?.event === "authz.cross_family_attempt",
    );
    expect(warnEvents.length).toBeGreaterThanOrEqual(1);
    const warnRec = warnEvents[0]!;
    expect(warnRec.payload.requesterUserId).toBe(familyA.userId);
    expect(warnRec.payload.resourceId).toBe(familyB.txId);
    expect(warnRec.payload.source).toBe("domain");
    // Core acceptance: the NOT_FOUND is logged with the requester's identity
    // for audit trail (FR-008 audit goal is met via both the error and the warn).
    expect(rec.payload.userId).toBe(familyA.userId);
  });
});
